### ISSUE TITLE
Recode plugin in task style

### ISSUE THREAD

**Issue by ItsJohnny30** [Endermanbugzjfc/FormInteractionFix#1]
I want Use Task Version Pls, I dont Want Await-Generate, thank you so much

**Comment by Endermanbugzjfc** [comment]
> I want Use Task Version Pls, I dont Want Await-Generate, thank you so much

煤撚驕李看呆麻麻

**Comment by Endermanbugzjfc** [comment]
> I want Use Task Version Pls, I dont Want Await-Generate, thank you so much

https://github.com/SOF3/await-generator/pull/174
只能幫到這了，如果真的有興趣的話請給點耐心。

**Comment by Endermanbugzjfc** [comment]
> [SOF3/await-generator#174](https://github.com/SOF3/await-generator/pull/174) 只能幫到這了，如果真的有興趣的話請給點耐心。

@johnnywai666 目前已完成 README 的翻譯： https://github.com/SOF3/await-generator/tree/master/chs

**Comment by Endermanbugzjfc** [comment]
> I want Use Task Version Pls, I dont Want Await-Generate, thank you so much

其實 https://github.com/Endermanbugzjfc/FormInteractionFix/actions 裏有 PHAR 下載。

**Comment by johnnywai666** [comment]
> 

????

**Comment by ItsJohnny30** [comment]
> > I want Use Task Version Pls, I dont Want Await-Generate, thank you so much
> 
> [SOF3/await-generator#174](https://github.com/SOF3/await-generator/pull/174) 只能幫到這了，如果真的有興趣的話請給點耐心。

谢谢你

**Comment by ItsJohnny30** [comment]
> > I want Use Task Version Pls, I dont Want Await-Generate, thank you so much
> 
> [SOF3/await-generator#174](https://github.com/SOF3/await-generator/pull/174) 只能幫到這了，如果真的有興趣的話請給點耐心。

我很期待呢!
